### ISSUE TITLE
Improve PAR failure error handling

### ISSUE THREAD

**Issue by josephdecock** [DuendeSoftware/foss#126]
When PAR fails, we aren't doing a great job of making it obvious that PAR is involved/the nature of the failure.

**Comment by alefcarlos** [comment]
@josephdecock,

I'm using PAR, then this exception is thrown when I access an authorized route(but only on release build):

```
dbug: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[9]
      AuthenticationScheme: OpenIdConnect was not authenticated.
fail: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[52]
      Message contains error: 'invalid_request', error_description: 'Invalid parameter: redirect_uri', error_uri: 'error_uri is null', status code '400'.
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: Message contains error: 'invalid_request', error_description: 'Invalid parameter: redirect_uri', error_uri: 'error_uri is null'.
         at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.GetPushedAuthorizationRequestUri(HttpResponseMessage parResponseMessage)
         at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.PushAuthorizationRequest(OpenIdConnectMessage authorizeRequest, AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsyncInternal(AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.<>c__DisplayClass0_0.<<HandleAsync>g__Handle|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

I had to disable that in OpenIdConnectOptions:

```
options.PushedAuthorizationBehavior = PushedAuthorizationBehavior.Disable;
```

But I have a question: should this opensource lib be throwing this exception ? Is it due to https://docs.duendesoftware.com/identityserver/v7/tokens/par/#licensing?

**Comment by bhazen** [comment]
Closing this due to inactivity. If anyone runs into a specific scenario where the PAR error handling could be improved, please open a new issue with the specifics of the scenario.
