### ISSUE TITLE
Fix service resolution in blazor server

### ISSUE THREAD

**Issue by kamil-gorny** [DuendeSoftware/foss#68]
**Which version of Duende.AccessTokenManagement are you using?**
Latest version pulled directly from the repository.

**Which version of .NET are you using?**
.NET 8 

**Describe the bug**
When attempting to connect a Blazor Server sample app to Azure SignalR and use Duende AccessTokenManagement, the application throws a NullReferenceException. The issue seems to originate from the BlazorServerUserAccessor, where dependencies like CircuitServicesAccessor and IHttpContextAccessor are null.

**To Reproduce**

1. Pull the latest version of Duende.AccessTokenManagement from the repository.
2. Set up a sample Blazor Server app.
3. Add Azure SignalR to the app:
```csharp
builder.Services.AddSignalR().AddAzureSignalR(options =>
{
    options.ServerStickyMode = ServerStickyMode.Required;
    options.ConnectionString = "insert your connection string here";
});
```

**Expected behavior**

The application should successfully retrieve the access token and make API calls without throwing exceptions. Dependencies like CircuitServicesAccessor and IHttpContextAccessor should be properly injected.

**Log output/exception with stacktrace**

```
Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer
Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Duende.AccessTokenManagement.OpenIdConnect.UserAccessAccessTokenManagementService.GetAccessTokenAsync(ClaimsPrincipal user, UserTokenRequestParameters parameters, CancellationToken cancellationToken) in /Users/kamilgorny/RiderProjects/Duende.AccessTokenManagement/src/Duende.AccessTokenManagement.OpenIdConnect/UserAccessTokenManagementService.cs:line 62
   at Duende.AccessTokenManagement.OpenIdConnect.OpenIdConnectUserAccessTokenHandler.GetAccessTokenAsync(Boolean forceRenewal, CancellationToken cancellationToken) in /Users/kamilgorny/RiderProjects/Duende.AccessTokenManagement/src/Duende.AccessTokenManagement.OpenIdConnect/OpenIdConnectUserAccessTokenHandler.cs:line 56
   at Duende.AccessTokenManagement.AccessTokenHandler.SetTokenAsync(HttpRequestMessage request, Boolean forceRenewal, CancellationToken cancellationToken, String dpopNonce) in /Users/kamilgorny/RiderProjects/Duende.AccessTokenManagement/src/Duende.AccessTokenManagement/AccessTokenHandler.cs:line 87
   at Duende.AccessTokenManagement.AccessTokenHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/kamilgorny/RiderProjects/Duende.AccessTokenManagement/src/Duende.AccessTokenManagement/AccessTokenHandler.cs:line 49
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at BlazorServer.Services.RemoteApiService.GetData() in /Users/kamilgorny/RiderProjects/Duende.AccessTokenManagement/samples/BlazorServer/Services/RemoteApiService.cs:line 25
   at BlazorServer.Pages.FetchRemoteData.OnInitializedAsync() in /Users/kamilgorny/RiderProjects/Duende.AccessTokenManagement/samples/BlazorServer/Pages/FetchRemoteData.razor:line 32
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

```

**Additional context**

I’ve tried various debugging approaches but haven’t been able to resolve this. I'm reaching out here because perhaps the creators or others in the community might have insights or ideas on what could be causing this issue and how to fix it

**Comment by josephdecock** [comment]
@kamil-gorny - looking at this again, I'm not certain if I reproduced exactly the same problem as you had. There is an issue in our sample code, which is that the server side token store keeps tokens in memory, but the store is now scoped and so its collection of tokens gets discarded. Changing ServerSideTokenStore in our BlazorServer sample app to have the tokens be static solves that problem for me:

```
    private static readonly ConcurrentDictionary<string, UserToken> _tokens = new();
```

And I'm able to at least add signalr and continue to use the sample app:
```
builder.Services.AddSignalR().AddAzureSignalR(options =>
        {
            options.ServerStickyMode = ServerStickyMode.Required;
            options.ConnectionString = "<REDACTED>";
        });
```

But the errors you saw were a little different so I'm wondering if this will fix it for you to. Can you please try changning the sample's store to have its _tokens be static and let us know how that works? Thanks!

**Comment by kamil-gorny** [comment]
@josephdecock -
Apologies for the delayed response, and thank you for revisiting this issue and suggesting the change to make _tokens static. Unfortunately, I’m still experiencing the same issue.

To help you better understand the problem, I’ve attached a video that demonstrates the behavior: [https://www.youtube.com/watch?v=BIC-ILADqwU&ab_channel=KamilG%C3%B3rny](https://www.youtube.com/watch?v=BIC-ILADqwU&ab_channel=KamilG%C3%B3rny) Hopefully, it will provide some useful insights.

If you have any further questions or need additional information, please let me know so we can work together to pinpoint the root cause.

Looking forward to your thoughts!

**Comment by josephdecock** [comment]
Hi, unfortunately I'm still struggling to reproduce the issue. In your video, it looks like you are making just small changes to the blazor server sample in the repo, but when I make the same changes things "work on my machine". Maybe we're working from a different starting point - what's the commit hash where you made those changes?

**Comment by Erwinvandervalk** [comment]
Hi, I've also tried to reproduce this issue and have been unable. As there has been no response to joe's question, i'm closing this issue. Should you still experience this issue and would like to collaborate, please re-open the issue or submit a new one.
